version: "3.8"

services:
  frontend:
    build:
      context: ./shiftrx-fe
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./shiftrx-be
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=shiftrx

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shiftrx
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
