import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "../redux/provider";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "./context/AuthProvider";
import { Header } from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ShiftRx",
  description: "Generated by Nicolas Buscaglia",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" bg-white">
      <body className={`${inter.className} `}>
        <Providers>
          <AuthProvider>
            <Header />
            <main>{children}</main>
            <Toaster />
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
